name: CI

on: 
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Publish to npm
        id: publish
        uses: JS-DevTools/npm-publish@v3
        with:
          strategy: all
          package: ./package.json
          access: public
          token: ${{ secrets.NPM_TOKEN }}
      - name: Publish GitHub release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.publish.outputs.version }}
          files: |
            *.tgz